# Generated by Django 3.2.10 on 2022-02-02 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_one', models.FloatField(blank=True, default=0, null=True)),
                ('point_two', models.FloatField(blank=True, default=0, null=True)),
                ('point_three', models.FloatField(blank=True, default=0, null=True)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('screenshot', models.ImageField(blank=True, upload_to='')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
